acme_test_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: AcmeTestBundle:Default:index }

create:
    path:     /create/
    defaults: { _controller: AcmeDemoBundle:Default:create }